version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/nestjs"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/graphql"
    schedule:
      interval: "weekly"

  - package-ecosystem: "yarn"
    directory: "/react"
    schedule:
      interval: "weekly"
