version: '3'
services:
  # Postgres
  database:
    container_name: database
    image: dnapostgres.azurecr.io/postgres:14
    # volumes:
    #   - ./data/database:/var/lib/postgresql/data
    networks:
      - dna_network
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'

  # cache:
  #   container_name: cache
  #   image: dnaredis.azurecr.io/redis:6
  #   networks:
  #     - dna_network

  # Directus
  directus:
    container_name: directus
    image: dnadirectus.azurecr.io/directus:latest
    ports:
      - 8055:8055
    # volumes:
    #   # By default, uploads are stored in /directus/uploads
    #   # Always make sure your volumes matches the storage root when using
    #   # local driver
    #   - ./uploads:/directus/uploads
    #   # Make sure to also mount the volume when using SQLite
    #   # - ./database:/directus/database
    #   # If you want to load extensions from the host
    #   # - ./extensions:/directus/extensions
    networks:
      dna_network:
        ipv4_address: '172.16.237.1'
    depends_on:
      - cache
      - database
    environment:
      KEY: 255d231b-5ea1-5996-9aa3-9225c1c43c2
      SECRET: 6116487b-cda1-52c2-b315-c8022c45e888

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

      # CACHE_ENABLED: 'true'
      # CACHE_STORE: 'redis'
      # CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: admin@email.com
      ADMIN_PASSWORD: 922530ec43c2

      ACCESS_TOKEN_TTL: 1d

  # NestJS
  nest:
    container_name: dnanestjs
    image: dnanestjs.azurecr.io/dnanestjs:v1
    build:
      context: .
      target: production
    command: npm run start:prod
    # volumes:
    #   - .:/usr/src/app
    #   - /usr/src/app/node_modules
    ports:
      - ${NEST_PORT}:${NEST_PORT}
      - 9229:9229
    env_file:
      - .env
    networks:
      - dna_network
    depends_on:
      - database
      - cache
      - directus

networks:
  dna_network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.237.0/16
