version: 1
directus: 9.5.1
collections:
  - collection: cat
    meta:
      collection: cat
      icon: null
      note: null
      display_template: null
      hidden: false
      singleton: false
      translations: null
      archive_field: null
      archive_app_filter: true
      archive_value: null
      unarchive_value: null
      sort_field: null
      accountability: all
      color: null
      item_duplication_fields: null
      sort: null
      group: null
      collapse: open
    schema:
      schema: public
      name: cat
      comment: null
fields:
  - collection: cat
    field: id
    type: integer
    schema:
      name: id
      table: cat
      schema: public
      data_type: integer
      is_nullable: false
      generation_expression: null
      default_value: nextval('cat_id_seq'::regclass)
      is_generated: false
      max_length: null
      comment: null
      numeric_precision: 32
      numeric_scale: 0
      is_unique: true
      is_primary_key: true
      has_auto_increment: true
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: cat
      field: id
      special: null
      interface: input
      options: null
      display: null
      display_options: null
      readonly: true
      hidden: true
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: cat
    field: user_created
    type: uuid
    schema:
      name: user_created
      table: cat
      schema: public
      data_type: uuid
      is_nullable: true
      generation_expression: null
      default_value: null
      is_generated: false
      max_length: null
      comment: null
      numeric_precision: null
      numeric_scale: null
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      foreign_key_schema: public
      foreign_key_table: directus_users
      foreign_key_column: id
    meta:
      collection: cat
      field: user_created
      special:
        - user-created
      interface: select-dropdown-m2o
      options:
        template: '{{avatar.$thumbnail}} {{first_name}} {{last_name}}'
      display: user
      display_options: null
      readonly: true
      hidden: true
      sort: null
      width: half
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: cat
    field: date_created
    type: timestamp
    schema:
      name: date_created
      table: cat
      schema: public
      data_type: timestamp with time zone
      is_nullable: true
      generation_expression: null
      default_value: null
      is_generated: false
      max_length: null
      comment: null
      numeric_precision: null
      numeric_scale: null
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: cat
      field: date_created
      special:
        - date-created
      interface: datetime
      options: null
      display: datetime
      display_options:
        relative: true
      readonly: true
      hidden: true
      sort: null
      width: half
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: cat
    field: user_updated
    type: uuid
    schema:
      name: user_updated
      table: cat
      schema: public
      data_type: uuid
      is_nullable: true
      generation_expression: null
      default_value: null
      is_generated: false
      max_length: null
      comment: null
      numeric_precision: null
      numeric_scale: null
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      foreign_key_schema: public
      foreign_key_table: directus_users
      foreign_key_column: id
    meta:
      collection: cat
      field: user_updated
      special:
        - user-updated
      interface: select-dropdown-m2o
      options:
        template: '{{avatar.$thumbnail}} {{first_name}} {{last_name}}'
      display: user
      display_options: null
      readonly: true
      hidden: true
      sort: null
      width: half
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: cat
    field: date_updated
    type: timestamp
    schema:
      name: date_updated
      table: cat
      schema: public
      data_type: timestamp with time zone
      is_nullable: true
      generation_expression: null
      default_value: null
      is_generated: false
      max_length: null
      comment: null
      numeric_precision: null
      numeric_scale: null
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: cat
      field: date_updated
      special:
        - date-updated
      interface: datetime
      options: null
      display: datetime
      display_options:
        relative: true
      readonly: true
      hidden: true
      sort: null
      width: half
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: cat
    field: name
    type: string
    schema:
      name: name
      table: cat
      schema: public
      data_type: character varying
      is_nullable: true
      generation_expression: null
      default_value: null
      is_generated: false
      max_length: 255
      comment: null
      numeric_precision: null
      numeric_scale: null
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: cat
      field: name
      special: null
      interface: input
      options: null
      display: null
      display_options: null
      readonly: false
      hidden: false
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: true
      group: null
relations:
  - collection: cat
    field: user_created
    related_collection: directus_users
    schema:
      constraint_name: cat_user_created_foreign
      table: cat
      column: user_created
      foreign_key_schema: public
      foreign_key_table: directus_users
      foreign_key_column: id
      on_update: NO ACTION
      on_delete: NO ACTION
    meta:
      many_collection: cat
      many_field: user_created
      one_collection: directus_users
      one_field: null
      one_collection_field: null
      one_allowed_collections: null
      junction_field: null
      sort_field: null
      one_deselect_action: nullify
  - collection: cat
    field: user_updated
    related_collection: directus_users
    schema:
      constraint_name: cat_user_updated_foreign
      table: cat
      column: user_updated
      foreign_key_schema: public
      foreign_key_table: directus_users
      foreign_key_column: id
      on_update: NO ACTION
      on_delete: NO ACTION
    meta:
      many_collection: cat
      many_field: user_updated
      one_collection: directus_users
      one_field: null
      one_collection_field: null
      one_allowed_collections: null
      junction_field: null
      sort_field: null
      one_deselect_action: nullify
