name: Build

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # 1) Setup node version
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      # 2) Cache npm installed modules on .npm
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 3) Install Nest node_modules
      - name: Install Nest dependencies
        run: npm install
        working-directory: nestjs

      # 4) Install React node_modules
      - name: Install React dependencies
        run: npm install
        working-directory: react

      # 5) Build Nest application
      - name: Build Nest
        run: npm run build
        working-directory: nestjs

      # 6) Build React application
      - name: Build React
        run: yarn build
        working-directory: react
