name: Dna NestJs Continous Integration

on:
  pull_request:
    branches: [main]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: action/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
        working-directory: nestjs
      - name: Run tests
        run: npm test
        working-directory: nestjs
      - name: Run build
        run: npm run build
        working-directory: nestjs
