name: Dna NestJs Continous Integration

on:
  pull_request:
    branches: [main]

jobs:
  dna_pull_request_run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm install
        working-directory: nestjs
      - name: Run tests
        run: npm test
        working-directory: nestjs
      - name: Run build
        run: npm run build
        working-directory: nestjs
