name: Testing & Building

on:
  pull_request:
    branches: [main]

jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        working-directory: nestjs
        with:
          node-version: "16"
          cache: "npm"

      # 1) Configuration
      - name: Install dependencies
        run: npm install
        working-directory: nestjs

      # 2) Generate tests with coverage report
      - name: Run tests
        run: npm run test:cov
        working-directory: nestjs

      # 3) Build Nest
      - name: Run build
        run: npm run build
        working-directory: nestjs
